# 添加需要编译的 Makefile 文件
MAKEFILE = Utility.makefile UDM.makefile Network.makefile Math.makefile Framework.makefile FSM.makefile BehaviorTree.makefile Database.makefile

include ../template/makefile.inc
