
#ifndef __GSLIB_FRIENDSYSTEM_MSGNUMIDFRIENDSYSTEM_H__
#define __GSLIB_FRIENDSYSTEM_MSGNUMIDFRIENDSYSTEM_H__

#include <GFLib/commonServer/message/message.h>
#include <GSLib/funType.h>
#include <GSLib/serverType.h>
#include <GSLib/baseDef.h>

namespace GSLib
{

namespace FriendSystem
{

enum EMsgNumIDFriendSystem
{	
	EMSGID_FRIENDSYSTEM_GC2CN_REQ_FRIENDS_OPEN	= 1,
	EMSGID_FRIENDSYSTEM_CN2GC_ACK_FRIENDS_OPEN,
	EMSGID_FRIENDSYSTEM_GC2CN_REQ_FRIENDS_ADD,
	EMSGID_FRIENDSYSTEM_CN2GC_REQ_FRIENDS_ADD_CONFIRM,
	EMSGID_FRIENDSYSTEM_GC2CN_ACK_FRIENDS_ADD_CONFIRM,
	EMSGID_FRIENDSYSTEM_CN2GC_NTF_FRIENDS_ADD_RESULT,
	EMSGID_FRIENDSYSTEM_GC2CN_REQ_FRIENDS_DEL,
	EMSGID_FRIENDSYSTEM_CN2GC_ACK_FRIENDS_DEL,
	EMSGID_FRIENDSYSTEM_GC2CN_REQ_FRIENDS_NEW_STRANGERS,
	EMSGID_FRIENDSYSTEM_CN2GC_ACK_FRIENDS_NEW_STRANGERS,
	EMSGID_FRIENDSYSTEM_GC2CN_REQ_FRIENDS_SEARCH,
	EMSGID_FRIENDSYSTEM_CN2GC_ACK_FRIENDS_SEARCH,
	EMSGID_FRIENDSYSTEM_GM2CN_NTF_FRIENDS_EXTEND_CAPACITY,
	EMSGID_FRIENDSYSTEM_GC2GM_REQ_FRIENDS_LOCAL,
	EMSGID_FRIENDSYSTEM_GM2GC_ACK_FRIENDS_LOCAL,
	EMSGID_FRIENDSYSTEM_CN2GM_NTF_FRIENDS_CHANGE,
};


enum EFriendSystemResult
{
	EFRIENDSYSTEM_RESUlT_SUCCESS = 0,
	EFRIENDSYSTEM_RESUlT_FAIL = 1,

};




}

}//GSLib

#endif
