# 添加需要编译的 Makefile 文件
MAKEFILE = ActivitySystem.makefile AchieveSystem.makefile ChatSystem.makefile DBSystem.makefile EquipSystem.makefile FriendSystem.makefile ItemSystem.makefile LoginSystem.makefile MailSystem.makefile
MAKEFILE += MasterSystem.makefile NPCSystem.makefile PetSystem.makefile PlayerSystem.makefile PrizeSystem.makefile RankSystem.makefile SceneSystem.makefile ShopSystem.makefile SkillSystem.makefile TaskSystem.makefile

include ../template/makefile.inc
