//////////////////////////////////////////////////////////////////////
//	created:	2014/11/24
//	filename: 	GSLib\taskSystem\GM\taskSystemError.h
//	author:		zhangming
//	
//	purpose:	
//////////////////////////////////////////////////////////////////////
#ifndef	__GSLIB_TASKSYSTEM_GM_TASKSYSTEM_ERROR_H__
#define __GSLIB_TASKSYSTEM_GM_TASKSYSTEM_ERROR_H__

#include <BSLib/utility/baseDef.h>

namespace GSLib
{

namespace TaskSystem
{

namespace GM
{

enum EGetTaskDailyListResult
{
	EGET_TASK_DAILY_LIST_RESULT_SUCCESS,
	EGET_TASK_DAILY_LIST_RESULT_FAIL,
	
};

enum EGetTaskMainListResult
{
	EGET_TASK_MAIN_LIST_RESULT_SUCCESS,
	EGET_TASK_MAIN_LIST_RESULT_FAIL,

};

enum EUpdateMainTaskStateResult
{
	EUPDATE_MAIN_TASK_STATE_RESULT_SUCCESS = 0,
	EUPDATE_MAIN_TASK_STATE_RESULT_FAIL,
	EUPDATE_MAIN_TASK_STATE_RESULT_INVALID_TASK_ID,
	EUPDATE_MAIN_TASK_STATE_RESULT_INVALID_TASK_STATE,
	EUPDATE_MAIN_TASK_STATE_RESULT_INVALID_REPORT_COUNT,
};

enum EGetDailyTaskPrizeResult
{
	EGET_DAILY_TASK_PRIZE_RESULT_SUCCESS,
	EGET_DAILY_TASK_PRIZE_RESULT_FAIL,
	EGET_DAILY_TASK_PRIZE_RESULT_NOT_EXIST,
	EGET_DAILY_TASK_PRIZE_RESULT_NOT_COMPLETE_YET,
	EGET_DAILY_TASK_PRIZE_RESULT_ALREADY_GOT_PRIZE,

};

enum EGetMainTaskPrizeResult
{
	EGET_MAIN_TASK_PRIZE_RESULT_SUCCESS,
	EGET_MAIN_TASK_PRIZE_RESULT_FAIL,
	EGET_MAIN_TASK_PRIZE_RESULT_NOT_EXIST,
	EGET_MAIN_TASK_PRIZE_RESULT_NOT_COMPLETE_YET,
	EGET_MAIN_TASK_PRIZE_RESULT_ALREADY_GOT_PRIZE,
};

enum EGetPetTaskResult
{
	EGET_PET_TASK_RESULT_SUCCESS = 0,
	EGET_PET_TASK_RESULT_FAIL,
};

enum ERefreshPetTaskResult
{
	EREFRESH_PET_TASK_RESULT_SUCCESS = 0,
	EREFRESH_PET_TASK_RESULT_FAIL,
	EREFRESH_PET_TASK_RESULT_NOT_ENOUGH_DIAMOND,
	EREFRESH_PET_TASK_RESULT_REACH_MAX_DAILY_COUNT,
};

enum EUpdatePetTaskStateResult
{
	EUPDATE_PET_TASK_STATE_SUCCESS = 0,
	EUPDATE_PET_TASK_STATE_FAIL,
	EUPDATE_PET_TASK_STATE_INVALID_TASK_INDEX,
	EUPDATE_PET_TASK_STATE_INVALID_TASK_STATE,
	EUPDATE_PET_TASK_STATE_INVALID_COUNT,
	EUPDATE_PET_TASK_STATE_REACH_DAILY_MAX_COUNT,
};

enum EGetPetTaskPrizeResult
{
	EGET_PET_TASK_PRIZE_SUCCESS = 0,
	EGET_PET_TASK_PRIZE_FAIL,
	EGET_PET_TASK_PRIZE_INVALID_TASK_INDEX,
	EGET_PET_TASK_PRIZE_INVALID_TASK_STATE,

};

}//GM

}//TaskSystem

}//GSLib

#endif//__GSLIB_TASKSYSTEM_GM_TASKDATAMGR_H__
