using System;
using System.Collections.Generic;
using System.Text;

namespace UnityGMClient
{
    class CTaskSystemMsgNumID
    {
        public const uint EMSGNUMID_TASKSYSTEM_GC2GM_REQ_GET_DAILY_TASK_LIST = 1;
        public const uint EMSGNUMID_TASKSYSTEM_GM2GC_ACK_GET_DAILY_TASK_LIST = 2;

        public const uint EMSGNUMID_TASKSYSTEM_GC2GM_REQ_GET_DAILY_TASK_PRIZE = 3;
        public const uint EMSGNUMID_TASKSYSTEM_GM2GC_ACK_GET_DAILY_TASK_PRIZE = 4;

        public const uint EMSGNUMID_TASKSYSTEM_GC2GM_REQ_GET_MAIN_TASK_LIST = 5;
        public const uint EMSGNUMID_TASKSYSTEM_GM2GC_ACK_GET_MAIN_TASK_LIST = 6;

        public const uint EMSGNUMID_TASKSYSTEM_GC2GM_REQ_GET_MAIN_TASK_PRIZE = 7;
        public const uint EMSGNUMID_TASKSYSTEM_GM2GC_ACK_GET_MAIN_TASK_PRIZE = 8;

        public const uint EMSGNUMID_TASKSYSTEM_GC2GM_NTF_FINISH_MAIN_TASK_EVENT = 9;
        public const uint EMSGNUMID_TASKSYSTEM_GM2GC_NTF_MAIN_TASK_STATE = 10;

        public const uint EMSGNUMID_TASKSYSTEM_GC2GM_REQ_NOTIFY_MAIN_TASK_UPDATE = 11; 
        public const uint EMSGNUMID_TASKSYSTEM_GM2GC_ACK_NOTIFY_MAIN_TASK_UPDATE = 12; 

        public const uint EMSGNUMID_TASKSYSTEM_GC2GM_REQ_GET_PET_TASK = 13;
        public const uint EMSGNUMID_TASKSYSTEM_GM2GC_ACK_GET_PET_TASK = 14; 

        public const uint EMSGNUMID_TASKSYSTEM_GC2GM_REQ_REFRESH_PET_TASK = 15; 
        public const uint EMSGNUMID_TASKSYSTEM_GM2GC_ACK_REFRESH_PET_TASK = 16; 

        public const uint EMSGNUMID_TASKSYSTEM_GC2GM_REQ_UPDATE_PET_TASK_STATE = 17; 
        public const uint EMSGNUMID_TASKSYSTEM_GM2GC_ACK_UPDATE_PET_TASK_STATE = 18; 

        public const uint EMSGNUMID_TASKSYSTEM_GC2GM_REQ_GET_PET_TASK_PRIZE = 19; 
        public const uint EMSGNUMID_TASKSYSTEM_GM2GC_ACK_GET_PET_TASK_PRIZE = 20; 


    }



}


