# 添加需要编译的 Makefile 文件
MAKEFILE = Server.makefile LoginServer.makefile SuperServer.makefile DataServer.makefile CenterServer.makefile GateServer.makefile GameServer.makefile

include ../template/makefile.inc
