
#ifndef __GSLIB_SHOPSYSTEM_MSGNUMIDSHOPSYSTEM_H__
#define __GSLIB_SHOPSYSTEM_MSGNUMIDSHOPSYSTEM_H__

#include <GFLib/commonServer/message/message.h>
#include <GSLib/funType.h>
#include <GSLib/serverType.h>
#include <GSLib/baseDef.h>

namespace GSLib
{

namespace ShopSystem
{

enum EMsgNumIDShopSystem
{
	EMSGID_SHOPSYSTEM_GC2GM_REQ_SHOP_OPEN	= 1,
	EMSGID_SHOPSYSTEM_GM2GC_ACK_SHOP_OPEN,
	EMSGID_SHOPSYSTEM_GC2GM_REQ_SHOP_BUY,
	EMSGID_SHOPSYSTEM_GM2GC_ACK_SHOP_BUY,
	EMSGID_SHOPSYSTEM_GC2GM_REQ_SHOP_REFRESH,
	EMSGID_SHOPSYSTEM_GM2GC_ACK_SHOP_REFRESH,
	EMSGID_SHOPSYSTEM_GC2GM_REQ_SHOP_PAID_REFRESH,
	EMSGID_SHOPSYSTEM_GM2GC_ACK_SHOP_PAID_REFRESH,
};


enum EShopSystemResult
{
	ESHOPSYSTEMRESULT_SUCCESS	= 1,
	ESHOPSYSTEMRESULT_FAILED,
};


enum EShopType
{
	ESHOPTYPE_PROP = 1, // 道具商场
	ESHOPTYPE_PVP,		// PVP商店
	ESHOPTYPE_DAILY,	// 日常限购商店
};


}

}//GSLib

#endif
