//////////////////////////////////////////////////////////////////////
//	created:	2014/10/09
//	filename: 	GSLib\taskSystem\msgNumIDTaskSystem.h
//	author:		mazhejiang
//	
//	purpose:	
//////////////////////////////////////////////////////////////////////
#ifndef __GSLIB_TASKSYSTEM_MSGNUMIDTASKSYSTEM_H__
#define __GSLIB_TASKSYSTEM_MSGNUMIDTASKSYSTEM_H__

#include <GFLib/commonServer/message/message.h>
#include <GSLib/funType.h>
#include <GSLib/serverType.h>
#include <GSLib/baseDef.h>

namespace GSLib
{

namespace TaskSystem
{

enum EMsgNumIDTestSystem
{
	EMSGNUMID_TASKSYSTEM_GC2GM_REQ_GET_DAILY_TASK_LIST = 1,
	EMSGNUMID_TASKSYSTEM_GM2GC_ACK_GET_DAILY_TASK_LIST = 2,

	EMSGNUMID_TASKSYSTEM_GC2GM_REQ_GET_DAILY_TASK_PRIZE = 3,
	EMSGNUMID_TASKSYSTEM_GM2GC_ACK_GET_DAILY_TASK_PRIZE = 4,

	EMSGNUMID_TASKSYSTEM_GC2GM_REQ_GET_MAIN_TASK_LIST = 5,
	EMSGNUMID_TASKSYSTEM_GM2GC_ACK_GET_MAIN_TASK_LIST = 6,

	EMSGNUMID_TASKSYSTEM_GC2GM_REQ_GET_MAIN_TASK_PRIZE = 7,
	EMSGNUMID_TASKSYSTEM_GM2GC_ACK_GET_MAIN_TASK_PRIZE = 8,

	EMSGNUMID_TASKSYSTEM_GC2GM_NTF_FINISH_MAIN_TASK_EVENT = 9,
	EMSGNUMID_TASKSYSTEM_GM2GC_NTF_MAIN_TASK_STATE = 10,

	EMSGNUMID_TASKSYSTEM_GC2GM_REQ_NOTIFY_MAIN_TASK_UPDATE = 11,
	EMSGNUMID_TASKSYSTEM_GM2GC_ACK_NOTIFY_MAIN_TASK_UPDATE = 12,

	EMSGNUMID_TASKSYSTEM_GC2GM_REQ_GET_PET_TASK = 13,
	EMSGNUMID_TASKSYSTEM_GM2GC_ACK_GET_PET_TASK = 14,

	EMSGNUMID_TASKSYSTEM_GC2GM_REQ_REFRESH_PET_TASK = 15,
	EMSGNUMID_TASKSYSTEM_GM2GC_ACK_REFRESH_PET_TASK = 16,

	EMSGNUMID_TASKSYSTEM_GC2GM_REQ_UPDATE_PET_TASK_STATE = 17,
	EMSGNUMID_TASKSYSTEM_GM2GC_ACK_UPDATE_PET_TASK_STATE = 18,

	EMSGNUMID_TASKSYSTEM_GC2GM_REQ_GET_PET_TASK_PRIZE = 19,
	EMSGNUMID_TASKSYSTEM_GM2GC_ACK_GET_PET_TASK_PRIZE = 20,
};

}//TaskSystem

}//GSLib

#endif//__GSLIB_TASKSYSTEM_MSGNUMIDTASKSYSTEM_H__
