#角色充值表
DROP TABLE IF EXISTS `RoleCharge`;
CREATE TABLE `RoleCharge`(
  `ChargeID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '充值ID,自动生成',
  `AccountID` BIGINT NOT NULL DEFAULT 0 COMMENT '玩家游戏唯一ID',
  `ZoneID` INT NOT NULL DEFAULT 0 COMMENT '游戏区ID',
  `RoleIndex` INT NOT NULL DEFAULT 0 COMMENT '角色索引',
  `PlatformAccount` VARCHAR(65) NOT NULL DEFAULT 0 COMMENT '游戏平台账号',
  `GameOrderID` VARCHAR(65) NOT NULL DEFAULT 0 COMMENT '游戏充值订单ID',
  `PlatformOrderID` VARCHAR(65) NOT NULL DEFAULT 0 COMMENT '平台充值订单ID',
  `Type` INT NOT NULL DEFAULT 0 COMMENT '商品类型',
  `Money` INT NOT NULL DEFAULT 0 COMMENT '充值金额',
  `SetTime` BIGINT NOT NULL DEFAULT '0' COMMENT '充值服务器写入时间',
  `GetTime` BIGINT NOT NULL DEFAULT '0' COMMENT '游戏服务器领取时间',
  `Platform` VARCHAR(16) NOT NULL DEFAULT 0 COMMENT '平台充值代号',
  PRIMARY KEY (`ChargeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '角色充值表';