#ifndef __GSLIB_DBTABLEID_H__
#define __GSLIB_DBTABLEID_H__

#include <GSLib/baseDef.h>

namespace GSLib
{

enum EDBTableID
{
	EDBTABLEID_NULL			= 0,//
	EDBTABLEID_ACCOUNT_DATA = 1,//AccountData
	EDBTABLEID_ROLE_DATA	= 2,//RoleData
	EDBTABLEID_PLAYER_DATA	= 3,//PlayerData
	EDBTABLEID_ROLE_SKILL_DATA	= 4,//RoleSkillData
	EDBTABLEID_ROLE_EQUIP_DATA	= 5,//RoleEquipData
	EDBTABLEID_ROLE_ITEM_DATA	= 6,//RoleItemData
	EDBTABLEID_ROLE_BAG_DATA	= 7,//RoleBagData
	
	EDBTABLEID_MAIL_OUTPUT_DATA			= 8,
	EDBTABLEID_ROLE_MAIL_CONFIG_DATA	= 9,
	EDBTABLEID_ROLE_MAIL_INPUTBOX_DATA	= 10,
	EDBTABLEID_ROLE_SCENE_ARENA_ROLE_DATA = 11,
	EDBTABLEID_ROLE_SCENE_ARENA_CHALLENGE_RECORD = 12,
	EDBTABLEID_ROLE_PET_DATA	= 13,//RolePetData
	//EDBTABLEID_PET_SKILL_DATA	= 14,//RolePetData
	EDBABLEID_ROLE_PRIZE_DATA	= 15,
	EDBABLEID_ROLE_DAILY_TASK_DATA	= 16,
	EDBTABLEID_ROLE_SHOP_DATA	= 17,
	EDBABLEID_ROLE_MAIN_TASK_DATA	= 18,
	EDBABLEID_ROLE_ATTENDENCE_DATA = 19,
	EDBTABLEID_ROLE_FRIEND_DATA = 20,
	EDBTABLEID_FRIEND_PENDING_QUEUE_DATA = 21,
    EDBTABLEID_ROLE_NAME_DATA = 22,
	EDBTABLEID_ROLE_STORY_INSTANCE_PROGRESS_DATA = 23,
	EDBTABLEID_ROLE_STAGE_DATA = 24,
	EDBTABLEID_ROLE_INSTANCE_PRIZE_DATA = 25,
	EDBTABLEID_RANK_DATA		= 26,
	EDBTABLEID_ROLE_DRAW_CARD_DATA = 27,
	EDBTABLEID_ROLE_CONTINUOUS_INSTANCE_DATA = 28,
	EDBTABLEID_ROLE_CONTINUOUS_INSTANCE_PROGRESS_DATA = 29,
	EDBTABLEID_ROLE_VIPGIFT_DATA = 30,
	EDBTABLEID_ROLE_RANK_DATA	= 31,
	EDBTABLEID_ROLE_CONTINUOUS_STAGE_RESULT_DATA = 32,
	EDBTABLEID_ROLE_RANK_CN_DATA		= 33,
    EDBTABLEID_ROLE_ACHIEVE_DATA = 34,
    EDBTABLEID_ROLE_STAGE_SYSTEM_DATA = 35,
	EDBABLEID_ROLE_PET_TASK_DATA = 36,
	EDBABLEID_ROLE_TASK_SYSTEM_DATA = 37,


	EDBTABLEID_MAX,

	//特殊意义定义
	EDBTABLEID_COMMAND						= 0X80000000,
	EDBTABLEID_COMMAND_INIT_PLAYER			= 0X80000001,//玩家初始化数据发送完成
	EDBTABLEID_COMMAND_INIT_PLAYER_FINSH	= 0X80000002,//玩家初始化数据发送完成
	EDBTABLEID_COMMAND_INIT_ROLE			= 0X80000003,//玩家初始化数据发送完成
	EDBTABLEID_COMMAND_INIT_ROLE_FINSH		= 0X80000004,//玩家初始化数据发送完成
	EDBTABLEID_COMMAND_INIT_SERVER			= 0X80000005,//玩家初始化数据发送完成
	EDBTABLEID_COMMAND_INIT_SERVER_FINSH	= 0X80000006,//玩家初始化数据发送完成
	EDBTABLEID_COMMAND_INIT_ROLE_END		= 0X80000007,//玩家初始化数据发送完成
};

}//GSLib

#ifdef __GNUC__

namespace __gnu_cxx
{
	template< > struct hash< GSLib::EDBTableID >
	{
		size_t operator()(const GSLib::EDBTableID& x) const
		{
			return (size_t)x;
		}
	};
}

#endif

#endif//__GSLIB_DBTABLEID_H__
