//////////////////////////////////////////////////////////////////////
//	created:	2014/09/10
//	filename: 	GSLib\petSystem\msgNumIDPetSystem.h
//	author:		mazhejiang
//	
//	purpose:	
//////////////////////////////////////////////////////////////////////
#ifndef __GSLIB_PETSYSTEM_MSGNUMIDPETSYSTEM_H__
#define __GSLIB_PETSYSTEM_MSGNUMIDPETSYSTEM_H__

#include <GFLib/commonServer/message/message.h>
#include <GSLib/funType.h>
#include <GSLib/serverType.h>
#include <GSLib/baseDef.h>

namespace GSLib
{

namespace PetSystem
{

	//////////////////////////////////////////////////////////////////////////
enum EMsgNumIDPetSystem
{
    // 温泉蛋
    EMSGNUMID_PETSYSTEM_GC2GM_REQ_EXPANDHOTSPRING = 1,
    EMSGNUMID_PETSYSTEM_GM2GC_ACK_EXPANDHOTSPRING = 2,
	// 初始化伙伴
	EMSGNUMID_PETSYSTEM_GM2GC_NTF_ACTIVE_SPRINGTASK = 3,     
	//EMSGNUMID_PETSYSTEM_GM2GC_NTF_HOTSPRINGEGG_FULL = 4,

	// 伙伴结束 
	EMSGNUMID_PETSYSTEM_GC2GM_REQ_HOTSPRINGTASK_END = 5,     
	EMSGNUMID_PETSYSTEM_GM2GC_ACK_HOTSPRINGTASK_END = 6,

	// 温泉任务完成
	EMSGNUMID_PETSYSTEM_GC2GM_REQ_PET_FINISHSPRINGTASK = 7,     
	EMSGNUMID_PETSYSTEM_GM2GC_ACK_PET_FINISHSPRINGTASK = 8,

	// 伙伴添加好友度 
	EMSGNUMID_PETSYSTEM_GC2GM_REQ_PET_GETPETUNLOCKDATA = 9,     
	EMSGNUMID_PETSYSTEM_GM2GC_ACK_PET_GETPETUNLOCKDATA = 10,

	// 冷却值清零
	EMSGNUMID_PETSYSTEM_GC2GM_REQ_UNLOCKPET = 11,     
	EMSGNUMID_PETSYSTEM_GM2GC_ACK_UNLOCKPET = 12,

	// 温泉老板娘任务 
	EMSGNUMID_PETSYSTEM_GC2GM_REQ_PET_SENDPET_GIFT = 13,
	EMSGNUMID_PETSYSTEM_GM2GC_ACK_PET_SENDPET_GIFT = 14,

    //EMSGNUMID_PETSYSTEM_GM2GC_NTF_UPDATE_HOTSPRING = 15,
    //EMSGNUMID_PETSYSTEM_GM2GC_NTF_ACTIVE_HOTSPRING_BOSSTASK = 16,

    EMSGNUMID_PETSYSTEM_GC2GM_REQ_GET_PET_BASEINFOR_LIST = 17, 
    EMSGNUMID_PETSYSTEM_GM2GC_ACK_GET_PET_BASEINFOR_LIST = 18,

    // 获取温泉任务详情
    EMSGNUMID_PETSYSTEM_GC2GM_REQ_PET_GET_HOTSPRING_TASK_DETAIL = 19,     
    EMSGNUMID_PETSYSTEM_GM2GC_ACK_PET_GET_HOTSPRING_TASK_DETAIL = 20,

    EMSGNUMID_PETSYSTEM_GC2GM_REQ_INIT_ROLEPETDATA = 21,
    EMSGNUMID_PETSYSTEM_GM2GC_ACK_INIT_ROLEPETDATA = 22,

    // 进入援护
    EMSGNUMID_PETSYSTEM_GC2GM_REQ_PET_SITDOWN = 23,
    EMSGNUMID_PETSYSTEM_GM2GC_ACK_PET_SITDOWN = 24,

    // 取消援护
    EMSGNUMID_PETSYSTEM_GC2GM_REQ_PET_STANDUP = 25,
    EMSGNUMID_PETSYSTEM_GM2GC_ACK_PET_STANDUP = 26,

    // 获取伙伴数据
    EMSGNUMID_PETSYSTEM_GC2GM_REQ_GET_PETDATA = 27,
    EMSGNUMID_PETSYSTEM_GM2GC_ACK_GET_PETDATA = 28,

    // 进入温泉
    EMSGNUMID_PETSYSTEM_GC2GM_REQ_PET_ENTERPOOL = 29,
    EMSGNUMID_PETSYSTEM_GM2GC_ACK_PET_ENTERPOOL = 30,

    // 离开温泉
    EMSGNUMID_PETSYSTEM_GC2GM_REQ_PET_QUITPOOL = 31,
    EMSGNUMID_PETSYSTEM_GM2GC_ACK_PET_QUITPOOL = 32,

    // 快速离开温泉
    EMSGNUMID_PETSYSTEM_GC2GM_REQ_PET_FAST_QUITPOOL = 33,
    EMSGNUMID_PETSYSTEM_GM2GC_ACK_PET_FAST_QUITPOOL = 34,
};

/// <summary>
/// 温泉扩建 
/// </summary>
enum EExpandHotSpringResult
{
    EEXPANDHOTSPRING_RESULT_SUCCESS = 0,
    EEXPANDHOTSPRING_RESULT_FAIL = 1,
    EEXPANDHOTSPRING_RESULT_LEVEL_LIMIT = 2,   // 达到温泉等级上限
    EEXPANDHOTSPRING_RESULT_DIAMOND_LIMIT = 3, // 钻石不足
    EEXPANDHOTSPRING_RESULT_VIPLEVEL_LIMIT = 4, // VIP等级不足(预留)
};

/// <summary>
/// 任务结束 
/// </summary>
enum EHotSpringTaskEndResult
{
    EHOTSPRINGTASK_END_RESULT_SUCCESS = 0,
    EHOTSPRINGTASK_END_RESULT_FAIL = 1,
    EHOTSPRINGTASK_END_RESULT_INVALID_PETID = 2, // 无效的伙伴ID
    EHOTSPRINGTASK_END_RESULT_INVALID_TASK = 3, // 当前任务无效
};

/// <summary>
/// 伙伴任务 
/// </summary>
enum EPetTaskFinishResult
{
    EPETTASKFINISH_RESULT_SUCCESS = 0,
    EPETTASKFINISH_RESULT_FAIL = 1,
    EPETTASKFINISH_RESULT_INVALID_PETID = 2, // 无效的伙伴ID
    EPETTASKFINISH_RESULT_INVALID_TASK = 3, // 当前任务无效
    EPETTASKFINISH_RESULT_ITEM_LIMIT = 4, // 数量不足或不存在该物品
};

/// <summary>
/// 伙伴送礼 
/// </summary>
enum ESendPetGiftResult
{
    ESENDPET_GIFT_RESULT_SUCCESS = 0,
    ESENDPET_GIFT_RESULT_FAIL = 1,
    ESENDPET_GIFT_RESULT_INVALID_PETID = 2, // 无效的伙伴ID
    ESENDPET_GIFT_RESULT_INVALID_GIFT = 3,  // 存在无效的礼物
    ESENDPET_GIFT_RESULT_ITEM_LIMIT = 4,  // 数量不足或不存在该物品
};

/// <summary>
/// 查看伙伴解锁进度 
/// </summary>
enum EGetPetUnlockDataResult
{
    EGETPETUNLOCKDATARESULT_SUCCESS = 0,
    EGETPETUNLOCKDATARESULT_FAIL = 1,
};

/// <summary>
///  解锁伙伴
/// </summary>
enum EUnlockPetResult
{
    EUNLOCKPET_RESULT_SUCCESS = 0,
    EUNLOCKPET_RESULT_FAIL = 1,
    EUNLOCKPET_RESULT_INVALID_PETTPID = 2, // 无效的伙伴TPID
    EUNLOCKPET_RESULT_METARIAL_LIMIT = 3,  // 伙伴合成材料不足
    EUNLOCKPET_RESULT_ALREADY_UNLOCK = 4,  // 伙伴已解锁
};

/// <summary>
/// 伙伴任务 
/// </summary>
enum EPetGetHotSpringTaskDetailResult
{
    EPETGET_HOTSPRING_TASKDETAIL_RESULT_SUCCESS = 0,
    EPETGET_HOTSPRING_TASKDETAIL_RESULT_FAIL = 1,
};

enum EGetInitRolePetDataResult
{
    EGET_INITROLEPETDATA_RESULT_SUCCESS = 0,
    EGET_INITROLEPETDATA_RESULT_FAIL = 1,
};

/// <summary>
/// 援护
/// </summary>
enum EPetSitDownResult
{
    EPETSITDOWN_RESULT_SUCCESS = 0,
    EPETSITDOWN_RESULT_FAIL = 1,
    EPETSITDOWN_RESULT_INVALID_PETID = 2,		// 伙伴不存在
    EPETSITDOWN_RESULT_ALREADY_SITDOWN = 3,		// 伙伴已经坐下（已经是援护状态）
    EPETSITDOWN_RESULT_ALREADY_INPOOL = 4,		// 伙伴在泡温泉（不可进入援护状态）
    EPETSITDOWN_RESULT_NO_SIT_PLACE,			// 已达到人数上限
};

/// <summary>
/// 取消援护
/// </summary>
enum EPetStandUpResult
{
    EPETSTANDUP_RESULT_SUCCESS = 0,
    EPETSTANDUP_RESULT_FAIL = 1,
    EPETSTANDUP_RESULT_INVALID_PETID = 2,   // 伙伴不存在
    EPETSTANDUP_RESULT_NOT_SITDOWN = 3,     // 伙伴不是援护状态
};

/// <summary>
/// 获取伙伴数据 
/// </summary>
enum EGetPetDataResult
{
    EGETPETDATA_RESULT_SUCCESS = 0,
    EGETPETDATA_RESULT_FAIL = 1,
    EGETPETDATA_RESULT_INVALID_PETID = 2,   // 伙伴不存在
};

/// <summary>
/// 进入温泉
/// </summary>
enum EPetEnterPoolResult
{
    EPETENTERPOOL_RESULT_SUCCESS = 0,
    EPETENTERPOOL_RESULT_FAIL = 1,
    EPETENTERPOOL_RESULT_INVALID_PETID = 2,   // 伙伴不存在
    EPETENTERPOOL_ALREADY_INPOOL = 3,         // 伙伴已在温泉中
    EPETENTERPOOL_ALREADY_SITDOWN = 4,        // 伙伴已援护，不可进入温泉中
    EPETENTERPOOL_ALREADY_FULL = 5,           // 温泉已满
};

/// <summary>
/// 离开温泉
/// </summary>
enum EPetQuitPoolResult
{
    EPETQUITPOOL_RESULT_SUCCESS = 0,
    EPETQUITPOOL_RESULT_FAIL = 1,
    EPETQUITPOOL_RESULT_INVALID_PETID = 2, // 伙伴不存在
    EPETQUITPOOL_RESULT_NOT_INPOOL = 3,    // 伙伴不温泉中
};

/// <summary>
/// 快速离开温泉
/// </summary>
enum EPetFastQuitPoolResult
{
    EPET_FASTQUITPOOL_RESULT_SUCCESS = 0,
    EPET_FASTQUITPOOL_RESULT_FAIL = 1,
    EPET_FASTQUITPOOL_RESULT_INVALID_PETID = 2,      // 伙伴不存在
    EPET_FASTQUITPOOL_RESULT_NOT_INPOOL = 3,         // 伙伴不温泉中
    EPET_FASTQUITPOOL_RESULT_DIAMOND_LIMIT = 4,      // 宝石不足
};

/// <summary>
/// 获取伙伴基本信息列表 
/// </summary>
enum EGetPetBaseInforListResult
{
    EGET_PETBASEINFORLIST_RESULT_SUCCESS = 0,
    EGET_PETBASEINFORLIST_RESULT_FAIL = 1,
};

}//PetSystem

}//GSLib

#endif//__GSLIB_PETSYSTEM_MSGNUMIDPETSYSTEM_H__
