#ifndef __GSLIB_SCENESYSTEM_MSGNUMIDSCENESYSTEM_H__
#define __GSLIB_SCENESYSTEM_MSGNUMIDSCENESYSTEM_H__

#include <GFLib/commonServer/message/message.h>
#include <GSLib/funType.h>
#include <GSLib/serverType.h>
#include <GSLib/baseDef.h>

namespace GSLib
{

namespace SceneSystem
{

enum EMsgNumIDTestSystem
{
	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_ENTER_SCENE = 1,
	 EMSGNUMID_SCENESYSTEM_GM2GC_ACK_ENTER_SCENE = 2,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_QUIT_SCENE = 3,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_QUIT_SCENE = 4,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_ROLE_REVIVE = 5,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_ROLE_REVIVE = 6,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_GET_ROLE_ARENA_DATA = 7,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_GET_ROLE_ARENA_DATA = 8,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_GET_NEW_ARENA_CHALLENGEES = 9,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_GET_NEW_ARENA_CHALLENGEES = 10,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_CHALLENGE_ARENA_ROLE = 11,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_CHALLENGE_ARENA_ROLE = 12,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_CHALLENGE_ARENA_ROLE_FINISH = 13,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_CHALLENGE_ARENA_ROLE_FINISH = 14,

	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_ADD_NEW_ARENA_CHALLENGE_RECORD = 16,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_GET_STORY_INSTANCE_PROGRESS = 17,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_GET_STORY_INSTANCE_PROGRESS = 18,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_GET_INSTANCE_DATA = 19,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_GET_INSTANCE_DATA = 20,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_ENTER_STAGE = 21,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_ENTER_STAGE = 22,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_STAGE_REPORT_RESULT = 23,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_STAGE_REPORT_RESULT = 24,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_CLEAR_STAGE = 25,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_CLEAR_STAGE = 26,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_GET_INSTANCE_STAR_PRIZE = 27,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_GET_INSTANCE_STAR_PRIZE = 28,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_GET_INSTANCE_STAR_PRIZE_PROGRESS = 29,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_GET_INSTANCE_STAR_PRIZE_PROGRESS = 30,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_GET_CONTINUOUS_INSTANCE_DATA = 31,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_GET_CONTINUOUS_INSTANCE_DATA = 32,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_ENTER_CONTINUOUS_STAGE = 33,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_ENTER_CONTINUOUS_STAGE = 34,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_REPORT_CONTINUOUS_STAGE_RESULT = 35,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_REPORT_CONTINUOUS_STAGE_RESULT = 36,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_ROLL_FAST_CLEAR_CONTINUOUS_STAGE_NUM = 37,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_ROLL_FAST_CLEAR_CONTINUOUS_STAGE_NUM = 38,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_RESET_CONTINUOUS_INSTANCE_DATA = 39,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_RESET_CONTINUOUS_INSTANCE_DATA = 40,

	EMSGNUMID_SCENESYSTEM_GM2GC_NTF_ROLE_ENTER_SCENE = 41,
	EMSGNUMID_SCENESYSTEM_GM2GC_NTF_ROLE_EXIT_SCENE = 42,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_ROLE_MOVE = 43,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_ROLE_MOVE = 44,
	EMSGNUMID_SCENESYSTEM_GM2GC_NTF_ROLE_MOVE = 45,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_DETERMINE_STAGE_PRIZE_ITEM = 47,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_DETERMINE_STAGE_PRIZE_ITEM = 48,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_ENTER_RANDOM_STAGE = 49,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_ENTER_RANDOM_STAGE = 50,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_SEND_RANDOM_STAGE_RESULT = 51,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_SEND_RANDOM_STAGE_RESULT = 52,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_GET_GREED_LAND_INFO = 53,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_GET_GREED_LAND_INFO = 54,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_PURCHASE_ARENA_TICKETS = 55,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_PURCHASE_ARENA_TICKETS = 56,

	EMSGNUMID_SCENESYSTEM_GC2GM_REQ_RESTORE_STAGE_TICKET = 57,
	EMSGNUMID_SCENESYSTEM_GM2GC_ACK_RESTORE_STAGE_TICKETS = 58,


	EMSGNUMID_SCENESYSTEM_GM2CN_REQ_ARENA_ACTION = 301,
	EMSGNUMID_SCENESYSTEM_GM2CN_ACK_ARENA_ACTION = 302,

};

}//SceneSystem

}//GSLib

#endif//__GSLIB_SCENESYSTEM_MSGNUMIDSCENESYSTEM_H__

