#ifndef __GSLIB_LOGINSYSTEM_MSGNUMIDLOGINSYSTEM_H__
#define __GSLIB_LOGINSYSTEM_MSGNUMIDLOGINSYSTEM_H__

#include <GFLib/commonServer/message/message.h>
#include <GSLib/funType.h>
#include <GSLib/serverType.h>
#include <GSLib/baseDef.h>

namespace GSLib
{

namespace LoginSystem
{

enum ELoginResult
{
	ELOGINRESULT_SUCCESS = 0,               //登录成功
	ELOGINRESULT_SUCCESS_FIRST = 1,         //登录成功，首次登陆
	ELOGINRESULT_ACCOUNT_NOTEXIST = 2,      //账号不存在
	ELOGINRESULT_PASSWORD_ERROR = 3,        //密码错误
	ELOGINRESULT_ZONEID_NOTEXIST = 4,       //游戏区不存在
	ELOGINRESULT_ZONEID_STOP = 5,           //游戏区停服
	ELOGINRESULT_CONNECT_ERROR = 6,         //链接服务器失败
	ELOGINRESULT_VERSION_DIFFERENCE = 7,    //客户端与服务器版本不一致
	ELOGINRESULT_SERVER_ERROR = 8,          //服务器异常
	ELOGINRESULT_ACCOUNT_LOGIN = 9, 		//账号正在登陆
	ELOGINRESULT_ACCOUNT_ONLINE = 10,	    //账号已经在游戏区
	ELOGINRESULT_LOGIN_TIMEOUT = 11,		//登陆超时
	ELOGINRESULT_LOGIN_CHECK_ERROR = 12,	//登陆参数验证不合法
	ELOGINRESULT_ACCOUNT_EXIT = 13, 		//账号正在退出
	ELOGINRESULT_TOKEN_ERROR = 14,			//TOKEN无效
};

enum ELoginType
{
	ELOGINTYPE_FAST_LOGIN,                 //快速登录
	ELOGINTYPE_NORMAL_LOGIN,               //普通登录
    ELOGINTYPE_TOKEN_LOGIN,                //token登录
};

enum ERegisterType
{
	EREGEITERTYPE_FAST_REGISTER,                 //快速注册
	EREGEITERTYPE_NORMAL_REGISTER,               //普通注册
	EREGEITERTYPE_BIND_MACHINE,                  //（绑定）
};

enum ERegisterResult
{
	EREGISTERRESULT_SUCCESS = 0,               //注册成功
	EREGISTERRESULT_ACCOUNT_EXIST = 1,         //账号或设备ID已经存在
	EREGISTERRESULT_ACCOUNT_INVALID = 2,       //账号或设备ID无效
    EREGISTERRESULT_ACTIVATION_CODE_INVALID = 3, // 激活码无效
};

enum EGetAccountTokenResult
{
    EGETACCOUNTTAKEN_SUCCESS = 0,               //登录成功
    EGETACCOUNTTAKEN_SUCCESS_FIRST = 1,         //登录成功，首次登陆
    EGETACCOUNTTAKEN_ACCOUNT_NOTEXIST = 2,      //账号不存在
    EGETACCOUNTTAKEN_PASSWORD_ERROR = 3,        //密码错误
    EGETACCOUNTTAKEN_CONNECT_ERROR = 6,         //链接服务器失败
    EGETACCOUNTTAKEN_VERSION_DIFFERENCE = 7,    //客户端与服务器版本不一致
    EGETACCOUNTTAKEN_SERVER_ERROR = 8,          //服务器异常
    EGETACCOUNTTAKEN_ACCOUNT_LOGIN = 9, 		//账号正在登陆
    EGETACCOUNTTAKEN_ACCOUNT_ONLINE = 10,	    //账号已经在游戏区
    EGETACCOUNTTAKEN_LOGIN_TIMEOUT = 11,		//登陆超时
    EGETACCOUNTTAKEN_LOGIN_CHECK_ERROR = 12,	//登陆参数验证不合法
    EGETACCOUNTTAKEN_ACCOUNT_EXIT = 13, 		//账号正在退出
    EGETACCOUNTTAKEN_TOKEN_ERROR = 14,			//TOKEN无效
};

enum EGetTokenType
{
    EGETTAKENTYPE_FAST_LOGIN,                 //快速登录
    EGETTAKENTYPE_NORMAL_LOGIN,               //普通登录
};


//////////////////////////////////////////////////////////////////////////
enum EMsgNumIDLoginSystem
{
	EMSGNUMID_LOGINSYSTEM_GC2LG_REQ_ACCOUNT_LOGIN = 1,
	EMSGNUMID_LOGINSYSTEM_LG2GC_ACK_ACCOUNT_LOGIN = 2,

	EMSGNUMID_LOGINSYSTEM_GC2GT_REQ_ACCOUNT_LOGIN = 3,
	EMSGNUMID_LOGINSYSTEM_GT2GC_ACK_ACCOUNT_LOGIN = 4,

	EMSGNUMID_LOGINSYSTEM_LG2CN_REQ_ACCOUNT_LOGIN = 5,
	EMSGNUMID_LOGINSYSTEM_CN2LG_ACK_ACCOUNT_LOGIN = 6,

	EMSGNUMID_LOGINSYSTEM_CN2GT_REQ_ACCOUNT_LOGIN = 7,
	EMSGNUMID_LOGINSYSTEM_GT2CN_ACK_ACCOUNT_LOGIN = 8,

	EMSGNUMID_LOGINSYSTEM_GT2CN_REQ_ACCOUNT_LOGIN = 9,
	EMSGNUMID_LOGINSYSTEM_CN2GT_ACK_ACCOUNT_LOGIN = 10,

	//创建Player协议
	EMSGNUMID_LOGINSYSTEM_CN2GT_REQ_CREATE_PLAYER = 11,
	EMSGNUMID_LOGINSYSTEM_GT2CN_ACK_CREATE_PLAYER = 12,

	EMSGNUMID_LOGINSYSTEM_CN2GM_REQ_CREATE_PLAYER = 13,
	EMSGNUMID_LOGINSYSTEM_GM2CN_ACK_CREATE_PLAYER = 14,

	EMSGNUMID_LOGINSYSTEM_CN2DB_REQ_CREATE_PLAYER = 15,
	EMSGNUMID_LOGINSYSTEM_DB2CN_ACK_CREATE_PLAYER = 16,

	//初始化Player协议
	EMSGNUMID_LOGINSYSTEM_CN2GT_REQ_INIT_PLAYER = 17,
	EMSGNUMID_LOGINSYSTEM_GT2CN_ACK_INIT_PLAYER = 18,

	EMSGNUMID_LOGINSYSTEM_CN2DB_REQ_INIT_PLAYER = 19,
	EMSGNUMID_LOGINSYSTEM_DB2CN_ACK_INIT_PLAYER = 20,

	EMSGNUMID_LOGINSYSTEM_DB2GM_REQ_INIT_PLAYER = 21,
	EMSGNUMID_LOGINSYSTEM_GM2DB_ACK_INIT_PLAYER = 22,

	EMSGNUMID_LOGINSYSTEM_GM2CN_NTF_INIT_PLAYER = 23,

	//EMSGNUMID_LOGINSYSTEM_GT2GM_NTF_PLAYER_INFOR_TO_CLIENT = 24,

	//离线协议
	EMSGNUMID_LOGINSYSTEM_GT2CN_REQ_ACCOUNT_BREAK = 25,
	EMSGNUMID_LOGINSYSTEM_CN2GT_ACK_ACCOUNT_BREAK = 26,

	EMSGNUMID_LOGINSYSTEM_CN2GT_REQ_ACCOUNT_OFFLINE = 27,
	EMSGNUMID_LOGINSYSTEM_GT2CN_ACK_ACCOUNT_OFFLINE = 28,
	
	EMSGNUMID_LOGINSYSTEM_CN2GM_REQ_ACCOUNT_OFFLINE = 29,
	EMSGNUMID_LOGINSYSTEM_GM2CN_ACK_ACCOUNT_OFFLINE = 30,
	
	EMSGNUMID_LOGINSYSTEM_CN2DB_REQ_ACCOUNT_OFFLINE = 31,
	EMSGNUMID_LOGINSYSTEM_DB2CN_ACK_ACCOUNT_OFFLINE = 32,

	//上线协议
	EMSGNUMID_LOGINSYSTEM_CN2GT_REQ_ACCOUNT_ONLINE = 33,
	EMSGNUMID_LOGINSYSTEM_GT2CN_ACK_ACCOUNT_ONLINE = 34,

	EMSGNUMID_LOGINSYSTEM_CN2GM_REQ_ACCOUNT_ONLINE = 35,
	EMSGNUMID_LOGINSYSTEM_GM2CN_ACK_ACCOUNT_ONLINE = 36,

	EMSGNUMID_LOGINSYSTEM_CN2DB_REQ_ACCOUNT_ONLINE = 37,
	EMSGNUMID_LOGINSYSTEM_DB2CN_ACK_ACCOUNT_ONLINE = 38,

	//退出协议
	EMSGNUMID_LOGINSYSTEM_GT2CN_NTF_ACCOUNT_QUIT = 39,
	EMSGNUMID_LOGINSYSTEM_CN2GT_REQ_ACCOUNT_FINAL = 40,
	EMSGNUMID_LOGINSYSTEM_GT2CN_ACK_ACCOUNT_FINAL = 41,
	EMSGNUMID_LOGINSYSTEM_GT2DB_NTF_ACCOUNT_FINAL = 42,

	EMSGNUMID_LOGINSYSTEM_GM2CN_NTF_ACCOUNT_QUIT = 43,
	EMSGNUMID_LOGINSYSTEM_CN2GM_REQ_ACCOUNT_FINAL = 44,
	EMSGNUMID_LOGINSYSTEM_GM2CN_ACK_ACCOUNT_FINAL = 45,
	EMSGNUMID_LOGINSYSTEM_GM2DB_NTF_ACCOUNT_FINAL = 46,

	EMSGNUMID_LOGINSYSTEM_DB2CN_NTF_ACCOUNT_QUIT = 47,
	EMSGNUMID_LOGINSYSTEM_CN2DB_REQ_ACCOUNT_FINAL = 48,
	EMSGNUMID_LOGINSYSTEM_DB2CN_ACK_ACCOUNT_FINAL = 49,

	EMSGNUMID_LOGINSYSTEM_GT2CN_NTF_ACCOUNT_TIMEOUT = 50,

	//广播消息
	EMSGNUMID_LOGINSYSTEM_XS2GT_NTF_BROADCAST_MSG = 51,

	EMSGNUMID_LOGINSYSTEM_GC2LG_REQ_REGISTER_ACCOUNT = 52,
	EMSGNUMID_LOGINSYSTEM_LG2GC_ACK_REGISTER_ACCOUNT = 53,

	EMSGNUMID_LOGINSYSTEM_LG2SP_REQ_REGISTER_TOKEN = 54,
	EMSGNUMID_LOGINSYSTEM_SP2LG_ACK_REGISTER_TOKEN = 55,

	EMSGNUMID_LOGINSYSTEM_LG2SP_REQ_CHECK_TOKEN = 56,
	EMSGNUMID_LOGINSYSTEM_SP2LG_ACK_CHECK_TOKEN = 57,

    EMSGNUMID_LOGINSYSTEM_GC2LG_REQ_GET_ACCOUNT_TAKEN = 58,
    EMSGNUMID_LOGINSYSTEM_LG2GC_ACK_GET_ACCOUNT_TAKEN = 59,

    EMSGNUMID_LOGINSYSTEM_GC2LG_REQ_TAKEN_LOGIN = 60,
    EMSGNUMID_LOGINSYSTEM_LG2GC_ACK_TAKEN_LOGIN = 61,

	EMSGNUMID_LOGINSYSTEM_SP2AC_REQ_CHECK_TAKEN = 62,
	EMSGNUMID_LOGINSYSTEM_AC2SP_ACK_CHECK_TAKEN = 63,
};

}//LoginSystem

}//GSLib

#endif//__GSLIB_LOGINSYSTEM_MSGNUMIDLOGINSYSTEM_H__

